package.json
=> Add support for react-native 0.12.0

.eslintrc, GooglePlacesAutocomplete.js, package.json
I tried linting the code using eslint, eslint-config-airbnb and eslint-plugin-react. I think those tools are really helpful to keep your code readable and maintainable over time.
I tried not to touch any module logic.
=> added eslint and linted the code

GooglePlacesAutocomplete.js
Updated dependencies due to https://github.com/facebook/react-native/releases/tag/v0.25.1
=> React upgrade fixes

GooglePlacesAutocomplete.js
all ability to set address text box from outside of component.
=> add setAddressText

GooglePlacesAutocomplete.js
Added prop to change placeholder text color. It gives an option to add placeholder text color according to the developers choice. Having it there makes it very intuitive and easy to incorporate as per the app design.
=> added prop to change placeholder text color

GooglePlacesAutocomplete.js
I have tweaked it a bit, styles etc... now it looks more like on demo [page](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete). Also, now it prevents appearing of separator for last item in the ListView. In my app it looks like as on screenshot
=> Move Google Places terms as footer in ListView

GooglePlacesAutocomplete.js
Yellowbox warnings are disabled accordingly if onNotFound or onFail are set.
=> Added onNotFound and onFail props; Added getAddressText method

GooglePlacesAutocomplete.js
There is styling issue on android which shows underline in the text input. For solution the underlineColorAndroid="transparent" prop should be used ;
<TextInput
{ ...userProps }
ref="textInput"
autoFocus={this.props.autoFocus}
style={[defaultStyles.textInput, this.props.styles.textInput]}
onChangeText={onChangeText ? text => {this._onChangeText(text); onChangeText(text)} : this._onChangeText}
value={this.state.text}
placeholder={this.props.placeholder}
placeholderTextColor={this.props.placeholderTextColor}
onFocus={onFocus ? () => {this._onFocus(); onFocus()} : this._onFocus}
clearButtonMode="while-editing"
underlineColorAndroid="transparent"
/>
=> Styling android

GooglePlacesAutocomplete.js
For some reason, there is no option to render buttons to the left and to the right of the TextInput. I've added this option by adding new _renderLeftButton_ and _renderRightButton_ which should be functions.
I think this would be very useful (at least I needed this option for my project)
peace
=> Side buttons

GooglePlacesAutocomplete.js
Since this was an open issue and i also encountered it, i tweaked the code a little to make it work on android
Cheers
=> added underlineColorAndroid #103

GooglePlacesAutocomplete.js, README.md, package.json
The title explains pretty much the content.
I guess I am not the only one wanting it:
https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/110
I haven't tested it much though.
Feel free to get back to me.
=> add debouncing capabilities

GooglePlacesAutocomplete.js, README.md, package.json
The callback was affection only the results from autocomplete list but it was missing the section after details of each row as fetched.
=> Add missing callback before setting the state

GooglePlacesAutocomplete.js
iOS fix for pointer events sent to container view
=> Container should not handle pointerEvents on iOS

GooglePlacesAutocomplete.js
The resizeMode prop of image needs a string
=> Change resize mode value of Image

GooglePlacesAutocomplete.js
trigger onFail event when error message are returned
=> trigger onFail event

GooglePlacesAutocomplete.js
if you changed your mind and finally don't want research somewhere so when you click anywhere you hide the list
=> fix onblur

README.md
Import correct react-native dependencies in first example
=> Update first example in README.md

GooglePlacesAutocomplete.d.ts
Hi, thank you for the great library.
It is helpful if there is type definitions file (`.d.ts`) for TypeScript user (like me).
I tried `npm install @types/react-native-google-places-autocomplete`, but unfortunately there are no type definitions in DefinitelyTyped.
Thank you.
=> Add TypeScript definitions (.d.ts) file

package.json
Fixes https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/504
https://www.npmjs.com/advisories/1469
=> Fix vulnerability of peer dependency

GooglePlacesAutocomplete.js
This PR fixes compatibility issue with react-native-web (or webpack in general)
reference:
(https://stackoverflow.com/questions/42449999/webpack-import-module-exports-in-the-same-module-caused-error)
=> compatibility with webpack (for RNW)

README.md
closes https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/428
=> Link out to docs for filterReverseGeocodingByTypes

GooglePlacesAutocomplete.d.ts
=> Add textInputProps property to GooglePlacesAutocompleteProps

GooglePlacesAutocomplete.d.ts
Reverts FaridSafi/react-native-google-places-autocomplete#560
=> Revert "Add textInputProps property to GooglePlacesAutocompleteProps"

GooglePlacesAutocomplete.d.ts
=> Added textInputProps property to GooglePlacesAutocompleteProps

GooglePlacesAutocomplete.d.ts, README.md
=> feat: add types and docs for instance methods

GooglePlacesAutocomplete.d.ts
=> Update location typescript definition

GooglePlacesAutocomplete.js
Adapted from #539 
Also removes blank pre-defined places.
Closes #495 #539
=> rebuild rows when predefined places change

GooglePlacesAutocomplete.d.ts
=> feat: add ForwardRefExoticComponent types

GooglePlacesAutocomplete.js
Reverts FaridSafi/react-native-google-places-autocomplete#649
=> Revert "add workaround for RNW onBlur firing too early"

README.md
Small readme fix. Example makes use of useRef rather than useState
=> Replace useState import with useRef import in example

GooglePlacesAutocomplete.js
There is no indicator to show that API is calling. Besides, I have also added the loaderColor, loadingText and styles.loadingText props.
=> loader to show that the google places api is loading places

GooglePlacesAutocomplete.d.ts
=> Fix TS GooglePlaceDetail#types

GooglePlacesAutocomplete.d.ts, GooglePlacesAutocomplete.js, README.md
=> Make getCurrentLocation accessible on the ref object

GooglePlacesAutocomplete.js
Fixes #668 
Solution taken from here: 
https://stackoverflow.com/a/54290946/7180620
=> Fix listViewDisplayed warning with propTypes

README.md
updated react-native-elements Input component docs link
=> docs: upd rn-elements "Input" component docs link

GooglePlacesAutocomplete.js
https://stackoverflow.com/a/3648331
=> Fix abort request

GooglePlacesAutocomplete.js, package.json
@FaridSafi We need to polish the re-render of functions due to missing useCallback later.
=> Fix old link used by request due to memo
