FaridSafi/react-native-google-places-autocomplete

README.md
Sorry! I found the previous ones a bit confusing. Since we're just calling the web service via HTTP, we need to make sure we're enabling the Web Service, not iOS or Android!
=> Update Google Places API instructions

GooglePlacesAutocomplete.js
I needed to focus on textInput after navigator transition is over. So, i needed to create a *triggerFocus* method and expose it for parent components.
I think this might be useful for others too.
=> expose a method to parent components to focus on text input manually

GooglePlacesAutocomplete.js
Hi,
This PR allows to pass a`textInputProps` that will be passed down to the `TextInput` component for further customization. Tell me if you have any remarks.
Thanks,
Paul
=> adding textInputProps prop to the autocomplete component

GooglePlacesAutocomplete.js
- Added "enablePoweredByContainer" property to hide "Powered By" area
- Added ability to submit custom "Special Items" -- useful to add "City" elements such as "Current Location":
- Added "Blur" container underneath the ListView that allows the user to cancel the edit mode by tapping out of the ListView area
=> Added enablePoweredByContainer prop, specialItems prop and tap-to-blur behavior

GooglePlacesAutocomplete.js
By adding this prop, I removed the react-native warning: “In the next
release empty section headers will be rendered. In this release you can
use ‘enableEmptySections’ flag to render empty section headers”.
=> Added enableEmptySections prop

GooglePlacesAutocomplete.js
As of [RN v0.26](https://github.com/facebook/react-native/releases/tag/v0.26.0) `PropTypes` is now strictly part of `react` instead of `react-native`.  Without importing it directly, I get undefined calls to `PropTypes` on RN v0.28.
=> Update to work with react-native > 0.24

GooglePlacesAutocomplete.js
Hi,
If you use a hash # in your query then it breaks the input. encodeURI() doesn't encode special characters: , / ? : @ & = + $ #. There is an alternative encodeURIComponent() which also encodes those ones.
=> replaced encodeURI with encodeURIComponent 

package.json
Added react-native in `peerDependencies`, it just produces an useful warning.
Use of `ActivityIndicator` in Android on previous versions of React Native (< 0.28) causes a crash which is not so easy to track.
=> update package.json with react-native peerDependencies

GooglePlacesAutocomplete.js
Use `ActivityIndicator `only otherwise following warnings occur
`Warning: You are manually calling a React.PropTypes validation function for theindeterminateprop onProgressBarAndroid. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`
=> Using ActivityIndicator instead of deprecated ActivityIndicatorIOS

GooglePlacesAutocomplete.js
I just change the row, to allow them to be scrollable, because sometimes you got long addresses, in the result and you can't really choose the right one because the Text is cut.
I also move the separator view in the `renderSeparator` function of the ListView.
=> Scrollable row for long items & use renderSeparator

GooglePlacesAutocomplete.js
The use of 'maximumAge' inside of navigator.geolocation inside of the currentLocation function doesn't work on Android devices. Removing this parameter fixes this.
=> Optionally exclude 'maximumAge' from navigator.geolocation

GooglePlacesAutocomplete.js
as `keyboardShouldPersistTaps={true}"` gives deprecation warning I added this to props and made it default to `"always"`
=> add keyboardShouldPersistTaps to props, default to „always“

GooglePlacesAutocomplete.js
Added the possibility to use the currentLocation to just get the current position from onPress function without using the nearbyPlacesAPIs
Also options ({enableHighAccuracy: true, timeout: 20000}) may not work on some devices (request timed out), so I added the possibility to disable the HighAccuracy through a prop.
=> Add possibility to fire onPress with currentLocation

GooglePlacesAutocomplete.js
Thanks for the amazing package, It is working perfectly but I think there is minor improvment need to be incorporated. While implementing I realize that you have specified a particular underlay color for the result list rows. It's better to make it dynamic so in this pull request I have added provision to pass underlay color  as a prop named **listUnderlayColor** and if user does not provide this prop then by default underlay color ("#c8c7cc") will get applied.
Let me know if any queries.
=> Add ability to change the underlay color of the result list

GooglePlacesAutocomplete.js
I have added scrollEnabled prop for ScrollView which will allow to scroll autocomplete list as per user preference. 
Also I have fixed some build errors from previous pull request comma(,) was missing in GooglePlacesAutocomplete.js file.
=> Added scrollEnabled prop to dynamically keep scroll on or off

GooglePlacesAutocomplete.js, README.md
I added this so we're able to change the keyboard return key type to something other than the default. There is a list of types here: https://facebook.github.io/react-native/docs/textinput.html#returnkeytype
To use, you'd simply add the returnKeyType to the props like so: `returnKeyType={'search'}`
=> Add feature for changing keyboard return key type

GooglePlacesAutocomplete.js
Added Referer request header as prop for the google-places-autocomplete component. This update allows for a restricted Google API key as seen in this issue:
https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/140
=> adding origin property update

GooglePlacesAutocomplete.js
Results that don't fit within the screen width would continue off the screen, however using `width` instead of `minWidth` for the `TouchableHighlight` style will show an ellipsis when running out of room. This is more user friendly.
=> Fixed search results disappearing off screen

GooglePlacesAutocomplete.js
When specifying a default value as a property, the results of this value aren't loaded. This means that the user has to make a change for the search results of the default value to appear. Having a default seems pointless since the user still has to modify it to see the search results.
I've fixed this by calling `_onChangeText` after the view is rendered. Now when the view is rendered the results for the default value are displayed.
=> Fixed default value not loading when the view is rendered

GooglePlacesAutocomplete.js
This warning appear only if currentLocation is enabled, and after you tap on it the warning is displayed:
So, the solution was to use the `id` instead of the `description` in the `keyExtractor`. And also applied a fixed id for the Current location row.
@esganzerla we already discussed a bit about this problem. I've tested it and it's working properly now. Please take a look at your earliest convenience and let me know if I should change something else. Thanks!
=> Fix warning: Each child in an array or iterator should have a unique "key" prop

GooglePlacesAutocomplete.js
This adds an ActivityIndicator displayed while the component searching for the latest query in the search bar. This avoids confusion on slow connections when a user inputs a location and there's no feedback.
=> Add activity indicator when searching for places

GooglePlacesAutocomplete.js
Only display the loading component if not set to `null` so that the results list can persist between searches if the loading component isn't desired. Without this, the results list will flash since it alternates between the FlatList and nothing if the prop is set to `null`
=> Only Show Loading Component if Set

GooglePlacesAutocomplete.js
A change was made to move `...userProps` to below all other props for the `TextInput`.  While this makes sense (in that you can override any prop now) in almost all instances, it does not make sense for `onChangeText` considering the user's custom event is called from the default behaviour anyway.
This simply forces the `TextInput` to always use the default `onChangeText`.
=> Fix custom onChangeText overriding default behaviour

GooglePlacesAutocomplete.js
I was having issues with the current location requests timing out on android. I switched the default highAccuracyLocation to false and this solved my issue.
[This is a related issue](https://github.com/facebook/react-native/issues/7495)
[Here is a sample repository showing the working change.](https://github.com/jmpridgen/google-places-autocomplete-sample)
=> Default current location search to low accuracy

GooglePlacesAutocomplete.js
This will fix the bug where when a default value is set, the field appears with the list open. 
The gist: If the component is not mounted (based on _isMounted) we don't display the list. Simple fix.
=> List will remain closed when component is mounted with default value

GooglePlacesAutocomplete.js
In my previous PR I fixed a bug where if default value was set, the list would show open. In this minor PR I attempt to maintain a more sensible functionality - if the component is autoFocus=true, we will show the list. Otherwise we won't.
=> open the list on default value if the item is auto-focused

.eslintrc, GooglePlacesAutocomplete.js
I am not sure if this is intended behavior, but it is working for my project. I wanted to filter out results for the autocompleted results but this was not implemented in the current version. I simply filtered the results after the google places request is completed.
=> Filter results by type for autocompletion also

GooglePlacesAutocomplete.js
listViewDisplayed is false, the listView should not show when text prop changes.  The listView was displayed itself when listViewDisplayed is false on re-renders.
=> Fix listView opening when listViewDisplayed is false

GooglePlacesAutocomplete.js
When the component mounts it runs `_onChangeText` but does not run `textInputProps.onChangeText`
=> Run user supplied onChangeText callback when component mounts

GooglePlacesAutocomplete.js
```
<TextInput
...
clearButtonMode="while-editing"
underlineColorAndroid={this.props.underlineColorAndroid}
{ ...userProps }
onChangeText={this._handleChangeText}
/>
```
```
const {
...
clearButtonMode,
...
} = this.props.textInputProps;
<TextInput
...
clearButtonMode={
clearButtonMode ? clearButtonMode : "while-editing"
}
underlineColorAndroid={this.props.underlineColorAndroid}
{ ...userProps }
onChangeText={this._handleChangeText}
/>
```
```
<GooglePlacesAutocomplete
...
textInputProps={{ clearButtonMode: "never" }}
/>
```
- #356
=> change clearButtonMode prop

GooglePlacesAutocomplete.js, README.md
A repeat of #166, which seems to have gotten lost in the mix.
Adds the ability to modify `TextInput`'s underlying `keyboardAppearance` property.
=> add ability to configure keyboardAppearance for TextInput component

GooglePlacesAutocomplete.js, README.md
This PR fixes the "typo" on the example parameter for GooglePlacesSearchQuery ([#358](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/358)), following the [Google Places Search Documentation](https://developers.google.com/places/web-service/search)
Old:
```js
GooglePlacesSearchQuery={{
// available options for GooglePlacesSearch API : https://developers.google.com/places/web-service/search
rankby: 'distance',
types: 'food'
}}
```
New: 
```js
GooglePlacesSearchQuery={{
// available options for GooglePlacesSearch API : https://developers.google.com/places/web-service/search
rankby: 'distance',
type: 'cafe'
}}
```
I also updated the type, since `food`  was not valid. See doc (place types 1) [here](https://developers.google.com/places/web-service/supported_types)
=> Fix parameter for GooglePlacesSearchQuery (types -> type)

GooglePlacesAutocomplete.js
Imagine you want to bias street search within a certain city or some named region,
with preProcess function passed as prop, one would be able to do the following:
This will prefix 'New York' to any text entered by the user, thus limiting the autocomplete suggestions.
preProcess: (text) => {
return 'New York ' + text
}
=> Add an input value pre-process for extra biasing ability

GooglePlacesAutocomplete.js
This adds the ability to define a custom header prop on top of the list results:
```
<GooglePlacesAutocomplete
renderHeaderComponent={input => <Text>{input}</Text>}
// ...
```
Also add disableScroll prop to disable scrolling on main FlatList.
=> Add custom header component prop.

GooglePlacesAutocomplete.js, GooglePlacesAutocompleteExample/Example.js, README.md
As specified in the google documentation, requiring all props when calling this endpoint `https://maps.googleapis.com/maps/api/place/details/json` will increase the bill. 💵
> Warning: If you do not specify at least one field with a request, or if you omit the fields parameter from a request, ALL possible fields will be returned, and you will be billed accordingly. This applies only to Place Details requests (_source_ : https://developers.google.com/places/web-service/details)
This PR add the possibility to specify parameters for this request by adding this : 
```
GooglePlacesDetailsQuery={{
fields: 'formatted_address'
}}
```
_Available options for GooglePlacesDetails API : https://developers.google.com/places/web-service/details_
=> Add possibility to specify options for the googlePlacesDetails query 

GooglePlacesAutocomplete.js
I am using react-native-paper in my project, this allows me to pass in react-native-paper TextInput instead which accepts the default input props plus additional props. A better way me be to pass a render function, but that's a little different design.
=> Allow custom input component

GooglePlacesAutocomplete.js
Ref: 
* https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/140
* https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/170
I'm not sure how Google API restriction has been changed since then, but to respond to https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/489
I remove `origin` from `query` and add `referer` to `props`.
According to [the Google doc](https://developers.google.com/places/web-service/autocomplete), `origin` parameter is
> origin — The origin point from which to calculate straight-line distance to the destination (returned as distance_meters). If this value is omitted, straight-line distance will not be returned. Must be specified as latitude,longitude.
e.g. `<GooglePlacesAutocomplete …
=> Handle invalid origin parameter for Restricted API Key

GooglePlacesAutocomplete.d.ts, GooglePlacesAutocomplete.js, README.md
This is a work in-progress PR for web support, addressing 2 issues.
1) Because we are using `module.exports` this was incompatible with webpack, and by extension Expo web, CRA, Next.js etc.
2) Making a GET request on the web doesn't work because of CORS issues.  This PR adds a prop that allows you to specify the request url for web requests, to make it easier to use a proxy server.
The bulk of the work in this PR was done in #514. 
closed #389
closes #414
closes #436
closes #499
closes #525
=> Web and Expo support

GooglePlacesAutocomplete.js, README.md
This PR fixes a crash when selecting `currentLocation` in React Native v0.60.0+, since `navigator.geolocation` was [deprecated in React Native v0.60.0](https://reactnative.dev/docs/geolocation.html).
Instead of including a geolocation library as a dependency, this requires that you define `navigator.geolocation = require('SOME_GEOLOCATION_LIBRARY')` somewhere in your app.
This also means we get compatibility for the web out of the box and the library remains backwards compatible. 
I also cleanup some of the examples in the Readme, but there is still a lot of work to do there.
closes #541 
closes #447 
closes #473
closes #493
=> Fix Navigator Crash

GooglePlacesAutocomplete.d.ts
I added some kinds of methods that can be used in the component reference
=> Add missing class types

GooglePlacesAutocomplete.js, README.md
This PR reverts #526 and entirely remove support for passing a referer header. 
This library is not compatible with restricted API keys, as we don't use the native or JS sdks. 
Still in progress:  Adding back the `origin` prop, ~either in this PR or a follow up~.
Edit: It looks like you can add `origin` directly to `query`, `GoogleReverseGeocodingQuery`, `GooglePlacesSearchQuery`,  or `GooglePlacesDetailsQuery`, depending on which API you use.
This closes #561.
=> remove referer prop

GooglePlacesAutocomplete.js
When you would select Current Location, the list would hide and you would have to click the search box again in order to see the results. 
Closes #496.
=> fix list hiding when selecting current location

GooglePlacesAutocomplete.d.ts
`enablePoweredByContainer` is [defined as a PropType](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L920) but not in the typescript definitions.
=> Added typescript definition for enablePoweredByContainer

GooglePlacesAutocomplete.d.ts
fixes #577  
I was getting ts errors when using onFail prop while using VSCode
=> adding onFail to type definition

GooglePlacesAutocomplete.d.ts
As far as I can see in examples, `textInputProps` is not a required prop. This PR fixes typescript definitions to make it optional
=> Typescript: make textInputProps optional

GooglePlacesAutocomplete.js
Fix usage of navigator.geolocation.getCurrentPosition is null
When use react-native-service-location like
```js
navigator.geolocation = require('react-native-geolocation-service');
```
When use this library it comes in `default` property. 
`navigator.geolocation.getCurrentLocation` is undefined but `navigator.geolocation.default.getCurrentLocation` is currently defined.
=> Fix usage with react-native-service-location

GooglePlacesAutocomplete.js
A proposed solution to the issue in #629 where result text is cut off when isRowScrollabe={false}
=> Fixes #629 - Results don't wrap

README.md
The useful requestUrl prop seems to require reading the source code to find the expected format at the minute (unless I am missing something!).
=> Update README.md to document the requestUrl prop

GooglePlacesAutocomplete.js
Second try...
Prevented call to `debounce` function on every state change.
Explanation...
Current implementation:
`const debounceData = useCallback(debounce(_request, props.debounce), []);`
This will call `debounce(_request, props.debounce)` on every state change (while you are typing).
It won't change the value of `const debounceData` because `useCallback` will execute only once, but `debounce` is executed every time. Correct implementation would be with `useMemo` that will also execute only once and as a result return debounced `_request` function.
=> fixed debounceData function definition

GooglePlacesAutocomplete.js
Pull the onChangeText through the spread, similar to onBlur / onFocus.
=> Fix onChangeText

README.md
This was nowhere to be found in the docs.
=> add custom input example

GooglePlacesAutocomplete.js
Should close #641.   
Some of the <TextInput /> refs were not always available. This PR should fix that.
=> add textInput refs directly on useImperativeHandle

GooglePlacesAutocomplete.js
Fix for #638.
For more of background on this, see these issues - https://github.com/necolas/react-native-web/issues/1773, https://github.com/facebook/react/issues/4210.
As a workaround (read - hack),  I added an empty default blur function.
Waiting for some indication from the community that this fix is effective.
=> add workaround for RNW onBlur firing too early

GooglePlacesAutocomplete.d.ts
Hello,
I have added the missing the typings for plus_code which is recently introduced.
https://cloud.google.com/blog/products/maps-platform/introducing-plus-codes-place-autocomplete-place-details-and-geocoding-help-you-serve-users-everywhere
=> plus_code feature added to type definition file

GooglePlacesAutocomplete.js
Since pressing the the list items are calling _onBlur in the _onPress function then we could trigger a blur only if the related target does not belong to the list with address items.
So a clean candidate solution could be:
1) Attach an ID to the FlatList containing the results with clickable items
2) Call the onBlur only if the tap or click is not inside the list with results
=> Fix onPress issue caused by blur event

GooglePlacesAutocomplete.js
This will allow the `_request` function to be ran when a new `props.query` is passed in. Currently while implementing session tokens, I am running into an issue https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/702 where the `props.query.sessiontoken` is being memoized. This is causing the incorrect sessiontoken to get attached to the `places/autocomplete` call. This will also fix https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/675.
=> Add props.query to useMemo dependency array

GooglePlacesAutocomplete.js
Since `const [dataSource, setDataSource] = useState(buildRowsFromResults([]));` only init once, so the later update on the `props.predefinedPlaces` will not make it rerender.
=> Fix updating props.predefinedPlaces

GooglePlacesAutocomplete.d.ts, GooglePlacesAutocomplete.js
Results from the search can be made to persist after the blur event has been fired and focus from the input is lost.
This is helpful in a variety of situations where the on screen keyboard needs to be hidden or focus pulled elsewhere with the results from the search still visible.
=> Allow Persistent Results

GooglePlacesAutocomplete.d.ts
Use `/** */` comment to support parameter hints in Visual Studio Code
Result:
=> Show parameter hints in VSCode

GooglePlacesAutocomplete.js
Replaced `?&input` with `?input` in autocomplete request url, this should fix filtering by type #686.
P.S. This is my first contribution to open source, please let me know if I did something wrong.
=> fix autocomplete url params

README.md
Installation section of README.md contains a broken link to the Google Places API documentation.
=> Fix broken link to Google Places API in README.md

GooglePlacesAutocomplete.d.ts, GooglePlacesAutocomplete.js, README.md
A more generalized version of https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/660 that allows arbitrary headers to be specified when using a custom `requestUrl`. It determines the headers at request time so that values can be specified dynamically.
Our use case is adding an Authorization header to proxied Google requests. The custom proxy allows us to append the Google API key server side so it is not exposed via app traffic (as we can not use a restricted key with this library). We also need to guard against unauthorized usage of the proxy.
Example usage:
```
requestUrl={{
url: MY_PROXY,
useOnPlatform: "all",
headers: {
Authorization: `Bearer ${accessToken}`,
},
```
=> Add header support when using custom request url

GooglePlacesAutocomplete.js
Currently the package is breaking if you do not inform `headers` on the `requestUrl` prop.
=> Update getRequestHeaders to always return an object

GooglePlacesAutocomplete.js
observe those 3 separators. heights look irregular. (ref the screenshot below)
<a href="https://ibb.co/mG9B7m1"><img src="https://i.ibb.co/zrX5w1j/Studio-Project.jpg" alt="Studio-Project" border="0"></a>
fixed it using `StyleSheet.harlineWidth`. now lines are of same height
=> fix: fix irregular separator height

GooglePlacesAutocomplete.js
It would be good to send the `event` object to the `onBlur` method set in `textInputProps` by the user. Otherwise, end users might have issues using libraries like `formik` for validation.
=> Added event object to `onBlur` method sent through `textInputProps`
